### PR TITLE
Opusfilter filters

### PR DESCRIPTION
**Pull request by jelmervdl**
Add opusfilters as choices to the list of included filters.

- [x] Add definitions for filters
- [x] Add definitions for preprocessors
- [x] Add UI for added parameter types
  - [x] list
  - [x] tuple
- [x] Export to opusfilter YAML
- [ ] Import (parts of) opusfilter YAML

### CODE REVIEW

**Comment by jelmervdl** [comment]
One thing I noticed was that opusfilter effectively loads all its dependencies on start. For long running processes this makes sense (detect import errors early on etc.) but for this runner it is a bit annoying.

Maybe there is an easy way to hook into importlib and only load a proxy module for some modules, and only when accessing of any of its components is noticed we load the actual module.

**Comment by svirpioj** [comment]
> One thing I noticed was that opusfilter effectively loads all its dependencies on start. For long running processes this makes sense (detect import errors early on etc.) but for this runner it is a bit annoying.

Is it some specific dependencies that cause trouble? I guess we could try to use dynamic import for those.

**Comment by jelmervdl** [comment]
I'm not sure which bit of it is causing it. I'm using importlib's LazyLoader at the moment, and that helps to shave it down to half but start-up time on my laptop is still 2.5 seconds.

I haven't looked at hooking up some measuring callbacks to lazyloader. I also imagine there are off-the-shelf tools out there that can help us measure and break down import times per package.

**Comment by svirpioj** [comment]
> Is it some specific dependencies that cause trouble? I guess we could try to use dynamic import for those.

Well, there was quite a few, with `python -X importtime` and `tuna` those were easy to find. Now on OpusFilter's develop branch, the slow modules are imported only when needed. Reduced the startup time on my computer something like 80%.

**Pull request merged**
